server:
  port: 8005

spring:
  application:
    name: sendsms-module
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false #连接数据库
    username: root
    password: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mybatis:
  mapper-locations: classpath:mapper/*.xml    #扫描mapper目录下的.xml文件
  type-aliases-package: com.checkzh.entities  #所有的Entity别名类所在包