server:
  port: 8005

spring:
  application:
    name: sendsms-module
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false #连接数据库
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml    #扫描mapper目录下的.xml文件
  type-aliases-package: com.checkzh.entities  #所有的Entity别名类所在包
